version: "3"

services:
  mongodb:
    image: mongo
    container_name: imovel-mongodb
    restart: always
    command: mongod --port ${DB_PORT}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    networks:
      - api-gateway_service-network

  imovel-service:
    image: node:alpine
    container_name: imovel-service
    restart: always
    env_file:
      - .env
    depends_on:
      - mongodb
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - api-gateway_service-network
    command: yarn dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  db_data:
networks:
  api-gateway_service-network:
    external: true
