version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-home:/var/jenkins_home
    environment:
      JENKINS_HOST_HOME: "/data/jenkins"
    ports:
      - "${PORT_WWW}:8080"
      - "${PORT_OTHER}:50000"

volumes: 
  jenkins-home: